### ISSUE TITLE
Concurrency error on startup

### ISSUE THREAD

**Issue by thedoctor** [armadillabs/GemJava#1]
As noted in the readme, this error pops up, but for me it happens every time I run the code.

```
[Thread-1] INFO co.gem.philosopher.Waiter - waiter serving ARISTOTLE
Exception in thread "Thread-1" java.lang.IllegalStateException: Actor has not been started
    at co.paralleluniverse.actors.Actor.ref(Actor.java:357)
    at co.gem.philosopher.Waiter.doRun(Waiter.java:39)
    at co.gem.philosopher.Waiter.doRun(Waiter.java:17)
    at co.paralleluniverse.actors.Actor.run0(Actor.java:691)
    at co.paralleluniverse.actors.ActorRunner.run(ActorRunner.java:51)
    at co.paralleluniverse.strands.Strand$SuspendableCallableRunnable.run(Strand.java:845)
    at java.lang.Thread.run(Thread.java:745)
```

Question: why does this happen and how could it be fixed?

**Comment by armadillabs** [comment]
Yea, this is a tricky one.  The Waiter thread decides to suicide at some eventual time.

Do you have the rest of the output from when you run it?

**Comment by thedoctor** [comment]
Sure:

```
(py) matt at velocity in ~/dev/gem/gembox/projects/GemJava on master*
$ gradle build run
:compileJava
Note: /Users/matt/dev/gem/gembox/projects/GemJava/src/main/java/co/gem/philosopher/Waiter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processResources UP-TO-DATE
:classes
:jar
:startScripts
:distTar
:distZip
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build
:run
objc[7422]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/matt/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.16/f0cacc3d21e1027c82006a7a6f6cf2cad86d2a4f/slf4j-simple-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/matt/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.0/435f7a4b8c59a70bcbdbdf964a0db10fc81eff6f/log4j-slf4j-impl-2.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[quasar] ERROR: Unable to instrument class co/gem/philosopher/Philosopher
co.paralleluniverse.fibers.instrument.UnableToInstrumentException: Unable to instrument co/gem/philosopher/Philosopher#think()V because of blocking call to java/lang/Thread#sleep(J)V
    at co.paralleluniverse.fibers.instrument.InstrumentMethod.possiblyWarnAboutBlocking(InstrumentMethod.java:280)
    at co.paralleluniverse.fibers.instrument.InstrumentMethod.callsSuspendables(InstrumentMethod.java:170)
    at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:261)
    at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
    at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:113)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:87)
    at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:185)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at co.gem.philosopher.Driver.main(Driver.java:22)
[quasar] ERROR: while transforming co/gem/philosopher/Philosopher: Unable to instrument co/gem/philosopher/Philosopher#think()V because of blocking call to java/lang/Thread#sleep(J)V
co.paralleluniverse.fibers.instrument.UnableToInstrumentException: Unable to instrument co/gem/philosopher/Philosopher#think()V because of blocking call to java/lang/Thread#sleep(J)V
    at co.paralleluniverse.fibers.instrument.InstrumentMethod.possiblyWarnAboutBlocking(InstrumentMethod.java:280)
    at co.paralleluniverse.fibers.instrument.InstrumentMethod.callsSuspendables(InstrumentMethod.java:170)
    at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:261)
    at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
    at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:113)
    at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:87)
    at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:185)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at co.gem.philosopher.Driver.main(java:22)
[main] INFO co.gem.philosopher.Philosopher - NIETCHE has awakened.
[main] INFO co.gem.philosopher.Philosopher - NIETCHE is thinking.
[main] INFO co.gem.philosopher.Philosopher - NIETCHE requests to eat.
[main] INFO co.gem.philosopher.Philosopher - ARISTOTLE has awakened.
[main] INFO co.gem.philosopher.Philosopher - ARISTOTLE is thinking.
[Thread-1] INFO co.gem.philosopher.Waiter - Waiter received request: RequestMessage(originator=Philosopher(label=NIETCHE, table=Table(forkArrayList=[co.gem.philosopher.Fork@3caadfa8, co.gem.philosopher.Fork@21e3c4f6, co.gem.philosopher.Fork@27e89ae8, co.gem.philosopher.Fork@45c74e63, co.gem.philosopher.Fork@2ffa8eec], seats=5), waiter=Waiter(eaters=[]), position=0, lFork=co.gem.philosopher.Fork@2ffa8eec, rFork=co.gem.philosopher.Fork@3caadfa8, rn=java.util.Random@10813b91, count=null), state=1)
[Thread-1] INFO co.gem.philosopher.Waiter - waiter serving NIETCHE
[NIETCHE] INFO co.gem.philosopher.Philosopher - NIETCHE got hold of his left fork.
[NIETCHE] INFO co.gem.philosopher.Philosopher - NIETCHE got hold of his right fork.
[NIETCHE] INFO co.gem.philosopher.Philosopher - NIETCHE is eating.
[NIETCHE] INFO co.gem.philosopher.Philosopher - NIETCHE is done eating.
[NIETCHE] INFO co.gem.philosopher.Philosopher - NIETCHE is thinking.
[Thread-1] INFO co.gem.philosopher.Waiter - Waiter received request: RequestMessage(originator=Philosopher(label=NIETCHE, table=Table(forkArrayList=[co.gem.philosopher.Fork@3caadfa8, co.gem.philosopher.Fork@21e3c4f6, co.gem.philosopher.Fork@27e89ae8, co.gem.philosopher.Fork@45c74e63, co.gem.philosopher.Fork@2ffa8eec], seats=5), waiter=Waiter(eaters=[NIETCHE]), position=0, lFork=co.gem.philosopher.Fork@2ffa8eec, rFork=co.gem.philosopher.Fork@3caadfa8, rn=java.util.Random@10813b91, count=null), state=2)
[Thread-1] INFO co.gem.philosopher.Waiter - waiter cleaning up NIETCHE
[main] INFO co.gem.philosopher.Philosopher - ARISTOTLE requests to eat.
[Thread-1] INFO co.gem.philosopher.Waiter - Waiter received request: RequestMessage(originator=Philosopher(label=ARISTOTLE, table=Table(forkArrayList=[co.gem.philosopher.Fork@3caadfa8, co.gem.philosopher.Fork@21e3c4f6, co.gem.philosopher.Fork@27e89ae8, co.gem.philosopher.Fork@45c74e63, co.gem.philosopher.Fork@2ffa8eec], seats=5), waiter=Waiter(eaters=[]), position=1, lFork=co.gem.philosopher.Fork@3caadfa8, rFork=co.gem.philosopher.Fork@21e3c4f6, rn=java.util.Random@77e0427d, count=null), state=1)
[Thread-1] INFO co.gem.philosopher.Waiter - waiter serving ARISTOTLE
[main] INFO co.gem.philosopher.Philosopher - SOCRATES has awakened.
[main] INFO co.gem.philosopher.Philosopher - SOCRATES is thinking.
Exception in thread "Thread-1" java.lang.IllegalStateException: Actor has not been started
    at co.paralleluniverse.actors.Actor.ref(Actor.java:357)
    at co.gem.philosopher.Waiter.doRun(Waiter.java:39)
    at co.gem.philosopher.Waiter.doRun(Waiter.java:16)
    at co.paralleluniverse.actors.Actor.run0(Actor.java:691)
    at co.paralleluniverse.actors.ActorRunner.run(ActorRunner.java:51)
    at co.paralleluniverse.strands.Strand$SuspendableCallableRunnable.run(Strand.java:845)
    at java.lang.Thread.run(Thread.java:745)
[main] INFO co.gem.philosopher.Philosopher - SOCRATES requests to eat.
[main] INFO co.gem.philosopher.Philosopher - PLATO has awakened.
[main] INFO co.gem.philosopher.Philosopher - PLATO is thinking.
[NIETCHE] INFO co.gem.philosopher.Philosopher - NIETCHE requests to eat.
[main] INFO co.gem.philosopher.Philosopher - PLATO requests to eat.
[main] INFO co.gem.philosopher.Philosopher - KANT has awakened.
[main] INFO co.gem.philosopher.Philosopher - KANT is thinking.
[main] INFO co.gem.philosopher.Philosopher - KANT requests to eat.
> Building 93% > :run^C
```

**Comment by armadillabs** [comment]
This is a pretty insidious issue, but unfortunately, I can provide a partial short fix for the symptom, and not the root cause because that will suck up quite a bit of time :).

The symptom is the Waiter that arbitrates between the resources (Table) and the client actors (Philosophers) is losing reference when trying to send a message back to the clients, and [this](https://github.com/armadillabs/GemJava/blob/hotfix/waiter-suicide/src/main/java/co/gem/philosopher/Waiter.java#L40) is causing it to die:

`m.getOriginator().ref().send(servingMessage);`

Short fix: Add a supervisor, and restart the Waiter node.  PR is [here](https://github.com/armadillabs/GemJava/pull/2).  It'll run until 100 requests have been served:

```
[Thread-1] INFO co.gem.philosopher.Waiter - waiter exhausted.
[ARISTOTLE] INFO co.gem.philosopher.Philosopher - ARISTOTLE got hold of his left fork.
[ARISTOTLE] INFO co.gem.philosopher.Philosopher - ARISTOTLE got hold of his right fork.
[ARISTOTLE] INFO co.gem.philosopher.Philosopher - ARISTOTLE is eating.
[NIETCHE] INFO co.gem.philosopher.Philosopher - NIETCHE requests to eat.
[ARISTOTLE] INFO co.gem.philosopher.Philosopher - ARISTOTLE is done eating.
[ARISTOTLE] INFO co.gem.philosopher.Philosopher - ARISTOTLE is thinking.
[ARISTOTLE] INFO co.gem.philosopher.Philosopher - ARISTOTLE requests to eat.
```

After which, a `waiter exhausted` message signifies a graceful shutdown of the waiter, while all philosopher threads will block on a reply from the now dead waiter.

Long fix: 
1.  [Register](http://docs.paralleluniverse.co/quasar/#clustering) all the actors in a cluster, and have each actor access a global registry for cluster awareness.
2.  Fix 1 should hopefully fix things, but resources should be contained AND managed within an actor (in this case, the Waiter), so their states can be easily shared by way of a message request from the clients.  Right now, a [Table reference](https://github.com/armadillabs/GemJava/blob/hotfix/waiter-suicide/src/main/java/co/gem/philosopher/Driver.java#L21) is shared among all actors, and that makes the restart logic hard when its necessary to bootstrap the cluster.
